### ISSUE TITLE
How to integrate a submodule into project?!?

### ISSUE THREAD

**Issue by lucaspdroz** [on2-dev/on2-website#1]
### How to integrate a submodule into project, removing the sub module and add it to the main project itself?
I've created with `hugo generate theme` the on2-theme, and for some reason it was created an submodule inside of the project reference, so i want to remove this submodule and integrate it at main project.

**Comment by jaydson** [comment]
First things first.
Where did you find this `generate` command?
A simple search in the official Hugo's docs I've found the command `hugo new theme [name] [flags]`
Here's the page: https://gohugo.io/commands/hugo_new_theme/

Here's a step by step example I just did:

![lucas-vs-hugo-1](https://user-images.githubusercontent.com/72206/87990218-f405c200-cab9-11ea-8e6c-ca1ff96117d5.jpg)
As you can see, I'm using the `new theme` command.  
Note that after run `hugo new theme` you end up a new Hugo project which contains a directory called `themes` and then your new generated theme.

![lucas-vs-hugo-2](https://user-images.githubusercontent.com/72206/87990225-f700b280-cab9-11ea-8adc-8a5731960e72.jpg)
As you can see, it seems like there's none Git module created.  
Here you can check more about Git modules (but I don't think it's necessary right now, as the theme is not using any module at all) https://git-scm.com/docs/git-submodule

**Comment by lucaspdroz** [comment]
## Solved
at theme `PATH`  remove `.git` from subsystem
`rm -r /themes/[Theme-Name]/.git`
then:
`git rm -r --cached on2-theme/`
This solved the problem.
